on: push

name: Windows Build

jobs:
  build:
    name: Windows Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          docker/run ./gradlew clean setupExe shadowJar
